import React, { useEffect, useState } from 'react';

interface NeuralLavaProps {
  isProcessing: boolean;
  generatedImage: string | null;
}

const NeuralLava: React.FC<NeuralLavaProps> = ({ isProcessing, generatedImage }) => {
  const [blobs, setBlobs] = useState<{ id: number; cx: string; cy: string; r: string; fill: string; duration: number }[]>([]);

  useEffect(() => {
    // Generate initial blobs
    const newBlobs = Array.from({ length: 6 }).map((_, i) => ({
      id: i,
      cx: `${30 + Math.random() * 40}%`,
      cy: `${20 + Math.random() * 60}%`,
      r: `${15 + Math.random() * 20}`,
      fill: i % 2 === 0 ? '#00f0ff' : '#ff2a6d', // neon-blue and alert magenta
      duration: 5 + Math.random() * 5
    }));
    setBlobs(newBlobs);
  }, []);

  return (
    <div className="w-64 h-full relative border-l border-white/5 bg-black/40 overflow-hidden backdrop-blur-md hidden lg:block rounded-r-sm">
      {/* SVG Filter for the Gooey Lava Effect */}
      <svg className="hidden">
        <defs>
          <filter id="gooey">
            <feGaussianBlur in="SourceGraphic" stdDeviation="15" result="blur" />
            <feColorMatrix in="blur" mode="matrix" values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 25 -10" result="gooey" />
            <feBlend in="SourceGraphic" in2="gooey" />
          </filter>
        </defs>
      </svg>

      {/* Lava Lamp Container */}
      <div 
        className={`absolute inset-0 transition-opacity duration-1000 ${generatedImage ? 'opacity-0' : 'opacity-100'}`}
        style={{ filter: "url(#gooey)" }}
      >
        <div className="w-full h-full relative opacity-50 mix-blend-screen">
          {blobs.map((blob) => (
            <div
              key={blob.id}
              className={`absolute rounded-full transition-all ease-in-out ${isProcessing ? 'animate-pulse' : ''}`}
              style={{
                left: blob.cx,
                top: blob.cy,
                width: `${blob.r}px`,
                height: `${blob.r * 1.5}px`, // Make them slightly oval
                backgroundColor: blob.fill,
                animation: `floatY ${isProcessing ? blob.duration / 2 : blob.duration}s infinite alternate ease-in-out, floatX ${isProcessing ? blob.duration / 1.5 : blob.duration * 1.5}s infinite alternate ease-in-out`
              }}
            />
          ))}
        </div>
      </div>

      {/* Generated Image Overlay */}
      {generatedImage && (
        <div className="absolute inset-0 p-4 flex flex-col justify-center animate-in fade-in duration-1000">
           <div className="border border-white/20 rounded-sm overflow-hidden shadow-[0_0_15px_rgba(0,240,255,0.2)]">
              <img src={generatedImage} alt="Generated by Neural Core" className="w-full object-cover" />
           </div>
           <p className="text-center text-[10px] text-gray-500 font-mono mt-4 uppercase tracking-widest">
             Rendered Visualization
           </p>
        </div>
      )}

      {/* Glass overlay lines */}
      <div className="absolute inset-0 pointer-events-none border-t-[50vh] border-b-[50vh] border-transparent border-l-[4px] border-l-white/5"></div>
      
      {/* Dynamic Keyframes for float */}
      <style>{`
        @keyframes floatY {
          0% { transform: translateY(-50px) scale(0.8); }
          100% { transform: translateY(50px) scale(1.2); }
        }
        @keyframes floatX {
          0% { transform: translateX(-20px); }
          100% { transform: translateX(20px); }
        }
      `}</style>

      <div className="absolute bottom-4 left-0 right-0 text-center text-[10px] text-gray-600 font-mono tracking-widest uppercase">
        Neural Core
      </div>
    </div>
  );
};

export default NeuralLava;
